ip: 10.1.164.45
servers:
- clusterid: 1
  clusterlayer: public
  endidx: 0
  portbase: 12001
  server: confsvr
  startidx: 0
- clusterid: 2001
  clusterlayer: zone
  endidx: 0
  portbase: 5001
  server: gatesvr
  startidx: 0
- clusterid: 2001
  clusterlayer: zone
  endidx: 0
  portbase: 5002
  server: gamesvr
  startidx: 0
- clusterid: 2001
  clusterlayer: zone
  endidx: 0
  portbase: 5021
  server: sessionsvr
  startidx: 0
- clusterid: 2000
  clusterlayer: world
  endidx: 0
  portbase: 4021
  server: ranksvr
  startidx: 0
wanip: 10.1.164.45
