ip: 10.1.164.45
servers:
- clusterid: 2001
  clusterlayer: zone
  endidx: 1
  portbase: 5001
  server: gatesvr
  startidx: 1
- clusterid: 2001
  clusterlayer: zone
  endidx: 3
  portbase: 5002
  server: gamesvr
  startidx: 1
- clusterid: 2001
  clusterlayer: zone
  endidx: 1
  portbase: 5021
  server: sessionsvr
  startidx: 1
- clusterid: 2000
  clusterlayer: world
  endidx: 1
  portbase: 4021
  server: ranksvr
  startidx: 1
wanip: 10.1.164.45
