ip: 1.0.0.2
servers:
- clusterid: 2001
  clusterlayer: zone
  endidx: 1
  portbase: 5001
  server: gatesvr
  startidx: 1
- clusterid: 2001
  clusterlayer: zone
  endidx: 3
  portbase: 5002
  server: gamesvr
  startidx: 1
- clusterid: 2001
  clusterlayer: zone
  endidx: 1
  portbase: 5021
  server: sessionsvr
  startidx: 1
wanip: 2.0.0.2
